<?php
/* lets see how cookies works.. so if we put in hour browser

create your php file called cookie_crisp.php:
    <?php
    print_r($_GET);
    ?>
now lets see what we take from GET function
But this in your browser and refresh:
http://localhost:8100/ex03/cookie_crisp.php?action=set&name=plat&value=choucroute

you will see:
Array ( [action] => set [name] => plat [value] => choucroute )

Perfect! Now lets see how to set a cookie:
    
    [documentation]    https://www.php.net/manual/en/function.setcookie.php
    The function works like this:
    setcookie ( string $name [, string $value = "" [, int $expires = 0 [, string $path = "" [, string $domain = "" [, bool $secure = FALSE [, bool $httponly = FALSE ]]]]]] ) : bool

So lets create something following this, we must give a name of the cookie a value (both strings) and
what time it expires. Note that it counts a the number of seconds past since "January 1, 1970", so we must use the function time() to take the time now
and we can set the time to expire for X seconds after now, 
    for example: time()+1200
    [check more](https://www.php.net/time)

    your php now is:
    <?php
    setcookie("baba", "yeeey", time()+1200);
    //print to check the cookie
    print_r($_COOKIE)
    ?>

    Now if you run curl -b you can record this cookie, you just must
    choose the name of the file.txt you wanna put this:
    
    $>  curl -b cook.txt 'http://localhost:8100/ex03/cookie_crisp.php'
    
    $>  cat cook.txt
                # Netscape HTTP Cookie File# https://curl.haxx.se/docs/http-cookies.html
                # This file was generated by libcurl! Edit at your own risk.

                localhost       FALSE   /ex03/  FALSE   1553810441      baba    yeeey

    ##Delete the cookie
    Now if you want to delete it you just put on your php
    baba is the name of the cookie, NULL is to clean the content, and 0 is to set the time in past.

            <?php
            setcookie("baba", NULL, 0);
            //print to see it:
            print_r($_COOKIE);
            ?>

    Then run curl -c command passing the name of the file you restore:
        
    $> curl -c cook.txt 'http://eXrXpX.42.fr:8xxx/ex03/cookie_crisp.php?action=set&name=plat&value=choucroute'
    
    if you run from the browser (http://localhost:8100/ex03/cookie_crisp.php) now will see:
        Array ( [sidebar_collapsed] => false )

    And if you cat your cook file.
                # Netscape HTTP Cookie File
                # https://curl.haxx.se/docs/http-cookies.html
                # This file was generated by libcurl! Edit at your own risk.

                localhost       FALSE   /ex03/  FALSE   1553809978      baba    deleted

    foreach ($_GET as $key => $value)
    //echo "$login: $value\n";

    //curl -c cook.txt 'http://eXrXpX.42.fr:8xxx/ex03/cookie_crisp.php?action=set&name=plat&value=choucroute'
    */
    //setcookie("thais", "tavelino", time()+1200);
    setcookie("baba", NULL, 0);
    //print to see it:
    print_r($_COOKIE);
?>